export type TiSOCodesFromMap = Partial<{
  Angola: "AO"
  Argentina: "AR"
  Australia: "AU"
  Azerbaijan: "AZ"
  Canada: "CA"
  China: "CN"
  Denmark: "DK"
  "United Kingdom": "GB"
  Greece: "GR"
  Indonesia: "ID"
  Italy: "IT"
  Japan: "JP"
  Malaysia: "MY"
  Norway: "NO"
  Oman: "OM"
  Philippines: "PH"
  "Papua New Guinea": "PG"
  Turkey: "TR"
  "New Zealand": "NZ"
  Chile: "CL"
  "Russian Federation": "RU"
  France: "FR"
  "United States": "US"
  "American Samoa": "AS"
  "Antigua and Barbuda": "AG"
  Bahamas: "BS"
  Comoros: "KM"
  "Cape Verde": "CV"
  "Cayman Islands": "KY"
  Cyprus: "CY"
  "Falkland Islands": "FK"
  "Faeroe Islands": "FO"
  "Federated States of Micronesia": "FM"
  "Saint Kitts and Nevis": "KN"
  Malta: "MT"
  "Northern Mariana Islands": "MP"
  Mauritius: "MU"
  "New Caledonia": "NC"
  "Puerto Rico": "PR"
  "French Polynesia": "PF"
  "Solomon Islands": "SB"
  "São Tomé and Principe": "ST"
  Seychelles: "SC"
  "Turks and Caicos Islands": "TC"
  Tonga: "TO"
  "Trinidad and Tobago": "TT"
  "United States Virgin Islands": "VI"
  Vanuatu: "VU"
  Samoa: "WS"
  "Canary Islands (Spain)": "IC"
  Guadeloupe: "GP"
  Fiji: "FJ"
}>
